// Built-in activity templates for quick creation
// Each template maps directly to the createActivity payload shape.

export const ACTIVITY_TEMPLATES = [
  {
    id: "morning-run",
    title: "Morning Run",
    description: "Start your day with a refreshing 5km run.",
    category: "Fitness",
    durationMin: 45,
    icon: "🏃",
    tags: ["cardio", "outdoors"],
    isPremium: false,
    defaultMood: "Energetic",
  },
  {
    id: "coffee-date",
    title: "Coffee Date",
    description: "Catch up with a friend over coffee.",
    category: "Social",
    durationMin: 60,
    icon: "☕",
    tags: ["cafe", "chat"],
    isPremium: false,
    defaultMood: "Warm",
  },
  {
    id: "meal-prep",
    title: "Meal Prep",
    description: "Plan and cook meals for the week.",
    category: "Food",
    durationMin: 120,
    icon: "🍳",
    tags: ["healthy", "home"],
    isPremium: false,
    defaultMood: "Productive",
  },
  {
    id: "movie-night",
    title: "Movie Night",
    description: "Relax with a favorite film and snacks.",
    category: "Relax",
    durationMin: 120,
    icon: "🎬",
    tags: ["home", "chill"],
    isPremium: false,
    defaultMood: "Cozy",
  },
  {
    id: "coding-session",
    title: "Coding Session",
    description: "Build something fun or learn a new library.",
    category: "Learning",
    durationMin: 90,
    icon: "💻",
    tags: ["dev", "project"],
    isPremium: false,
    defaultMood: "Focused",
  },
];
